### ISSUE TITLE
Pandas version and 03.02-Data-Indexing-and-Selection

### ISSUE THREAD

**Issue by GrahamDumpleton** [jakevdp/PythonDataScienceHandbook#5]
The ``requirements.txt`` file has:

```
pandas==0.18.1
```

yet 03.02-Data-Indexing-and-Selection fails with:

```
AttributeErrorTraceback (most recent call last)
<ipython-input-5-8721e0616114> in <module>()
----> 1 list(data.items())

/opt/app-root/lib/python2.7/site-packages/pandas/core/generic.pyc in __getattr__(self, name)
   2666         if (name in self._internal_names_set or name in self._metadata or
   2667                 name in self._accessors):
-> 2668             return object.__getattribute__(self, name)
   2669         else:
   2670             if name in self._info_axis:

AttributeError: 'Series' object has no attribute 'items'
```

So maybe is meant to be pandas 0.19.1.

**Comment by jakevdp** [comment]
Series has an ``items`` attribute in Python 3.X

**Comment by GrahamDumpleton** [comment]
It was in 0.19.1 for Python 2 as well, just not 0.18.1 which requirements.txt initially had.

**Comment by jakevdp** [comment]
It works in 0.18.1 on Python 3.X. That's why I closed the issue.

**Comment by jakevdp** [comment]
To make the requirements more clear, I added a note about the Python version in the README 325cf730d9c99ed8a8e03dd171e89333a7550ce7

**Comment by jakevdp** [comment]
All notebooks should also have Python 3.5 set in their kernel metadata as well.
